<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Khansa Tatimah">
<meta name="dcterms.date" content="2024-01-20">

<title>Pengaruh Harga Beras dan Pendapatan Per Kapita Terhadap Konsumsi Beras di Indonesia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Harga Beras dan Pendapatan Per Kapita Terhadap Konsumsi Beras di Indonesia</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Khansa Tatimah </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 20, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img" width="341"></p>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Pangan merupakan satu dari tiga kebutuhan primer penting dalam hidup yang harus dipenuhi oleh manusia. Dalam hal ini, beras menjadi makanan pokok yang selalu diusahakan ada di setiap rumah tangga. Hal ini dapat dilihat dari salah satu pameo lama yang berbunyi ana dina ana upa, yang berarti “ada hari ada butir nasi”. Keterkaitannya dengan harga,pendapatan dan tingkat konsumsi menjadi semakin jelas ketika dilihat dari perspektif ekonomi rumah tangga.</p>
<p>Harga beras menjadi faktor penting dalam menentukan tingkat inflasi dan stabilitas pasar pangan. Perubahan harga beras dapat secara langsung mempengaruhi daya beli masyarakatnya, terutama bagi masyarakat dengan pendapatan rendah yang memiliki proporsi besar dalam pengeluaran pangan.Hal ini sesuai dengan hasil penelitian terdahulu yang di lakukan oleh (Darma et al., 2018) bahwa dampak dari kenaikan harga suatu komoditas seperti sembako berakibat pada meningkatnya inflasi di Indonesia.</p>
<p>Pendapatan per kapita sering digunakan sebagai indikator kesejahteraan negara, standar pertumbuhan kemakmuran negara, sebagai pedoman bagi pemerintah dalam membuat kebijakan ekonomi, dan pembanding tingkat kemakmuran antarnegara.</p>
<p>Kiptia, 2018, dalam penelitiannya menyatakan bahwa harga kebutuhan pokok berpengaruh positif terhadap konsumsi masyarakat, karena konsumsi kebutuhan pokok tidak akan menurun meskipun harga naik atau turun.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Dalam penelitian ini penulis mengambil objek penelitian dari Badan Pusat Statistik (BPS). Ruang lingkup pembahasan terdiri dari tiga variable, yaitu harga beras, pendapatan per kapita dan konsumsi beras. Data yang digunakan adalah data time series yaitu dalam kurun waktu 2013-2022.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Hipotesis yang diajukan sebagai jawaban sementara terhadap permasalahan yang diajukan dalam penelitian ini yaitu:</p>
<p>H0 : Tidak ada hubungan signifikan antara konsumsi beras (y) dengan harga beras (x) atau pendapatan per kapita (s).</p>
<p>H1 : Ada hubungan signifikan antara konsumsi beras (y) dengan harga beras (x) atau pendapatan per kapita (s)</p>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan dari penelitian ini adalah untuk mengetahui hubungan antara harga beras, perdapatan per kapita dan konsumsi beras di Indonesia. Adapun manfaat dari penelitian ini antara lain:</p>
<p><strong>a. Bagi Penulis</strong></p>
<ol type="1">
<li>Proses penelitian memberikan kesempatan kepada penulis untuk mendapatkan pemahaman yang lebih mendalam tentang topik tersebut dan meningkatkan keterampilan penelitian.</li>
<li>Temuan yang menarik dapat membuka peluang untuk penelitian lanjutan, proyek kolaboratif, dan pengembangan lebih lanjut. Juga menjadi bahan referensi atas topik terkait.</li>
</ol>
<p><strong>b. Bagi Instansi</strong></p>
<ol type="1">
<li>Hasil penelitian dapat menjadi sumber informasi yang berharga untuk pihak-pihak yang terlibat dalam pengambilan keputusan, penelitian lanjutan, dan analisis pasar.</li>
<li>Analisis terkait dapat memberikan kontribusi terhadap perumusan kebijakan pangan dan ketahanan pangan di Indonesia.</li>
</ol>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Harga adalah sejumlah uang yang ditukarkan untuk sebuah produk atau jasa (Kotler dan Amstrong, 2016). Harga adalah jumlah nilai yang diberikan oleh pelanggan untuk mendapatkan keuntungan dari memiliki atau menggunkan suatu produk atau jasa.</p>
<p>Pendapatan perkapita menurut Sukirno (2004) adalah pendapatan rata-rata penduduk suatu negara atau daerah pada suatu periode tertentu yang biasanya satu tahun.</p>
<p>Konsumsi merupakan kegiatan belanja untuk keperluan rumah tangga barang dan jasa (Mankiw, 2006). Konsumsi adalah aktivitas belanja barang dan jasa yang dilakukukan oleh rumah tangga. konsumsi sebagai pembelanjaan yang dilakukan oleh seseoarang atas barang dan jasa dengan tujuan untuk memenuhi kebutuhan.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<colgroup>
<col style="width: 9%">
<col style="width: 23%">
<col style="width: 28%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Tahun</th>
<th>Harga Beras (X)</th>
<th>Konsumsi Beras (Y)</th>
<th>Pendapatan Per Kapita (S)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2013</td>
<td>10,869.00</td>
<td>28,345.54</td>
<td>38,370,000</td>
</tr>
<tr class="even">
<td>2014</td>
<td>11,500.00</td>
<td>28,692.11</td>
<td>41,900,000</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>12,806.00</td>
<td>29,178.94</td>
<td>45,120,000</td>
</tr>
<tr class="even">
<td>2016</td>
<td>13,191.00</td>
<td>29,150.00</td>
<td>47,960,000</td>
</tr>
<tr class="odd">
<td>2017</td>
<td>13,227.00</td>
<td>29,133.51</td>
<td>51,890,000</td>
</tr>
<tr class="even">
<td>2018</td>
<td>14,048.00</td>
<td>29,570.00</td>
<td>55,990,459</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>11,633.00</td>
<td>28,930.00</td>
<td>59,065,348.9</td>
</tr>
<tr class="even">
<td>2020</td>
<td>11,713.00</td>
<td>29,370.00</td>
<td>56,000,000</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>11,542.00</td>
<td>30,040.00</td>
<td>62,300,000</td>
</tr>
<tr class="even">
<td>2022</td>
<td>11,617.00</td>
<td>30,200.00</td>
<td>71,000,000</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="bps.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>Penelitian ini menggunakan data sekunder dengan bentuk data&nbsp;<em>time series</em>&nbsp;2013-2022, data yang dipakai ialah data yang telah diolah dengan sumber Badan Pusat Statistik.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>) </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data_uasS <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/LENOVO/Documents/SMT 3/UAS Metopen/data uasS.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x<span class="sc">+</span>s,<span class="at">data=</span>data_uasS)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>data_uasS<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_uasS<span class="sc">$</span>x, data_uasS<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Harga Beras"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh error terhadap harga beras</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>) </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data_uasS <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/LENOVO/Documents/SMT 3/UAS Metopen/data uasS.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x<span class="sc">+</span>s,<span class="at">data=</span>data_uasS)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>data_uasS<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_uasS<span class="sc">$</span>x, data_uasS<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Konsumsi Beras"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh error terhadap konsumsi beras</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Penelitian ini menggunakan regresi multivariat atau regresi berganda dengan 2 variabel independen 1 variabel dependen yaitu konsumsi beras. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
Y =\beta_0 + \beta_1 X+\beta_2S+ \mu
\]</span> Dimana:</p>
<p><em>Y</em> adalah variabel dependen (konsumsi beras).</p>
<p><em>X</em> adalah variabel independen pertama (harga beras).</p>
<p><em>S</em> adalah variabel independen kedua (pendapatan per kapita).</p>
<p><em>β</em>0​ adalah intercept (konstanta).</p>
<p><em>β</em>1​ dan <em>β</em>2​ adalah koefisien regresi yang menunjukkan dampak perubahan harga dan pendapatan terhadap konsumsi.</p>
<p><em>ϵ</em> adalah kesalahan acak atau faktor yang tidak dapat dijelaskan oleh model.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tabel.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>Hasil regresi yang telah didapat dimasukkan ke dalam rumus persamaan yang ada, sehingga menjadi:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Screenshot%202024-01-21%20012802.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>Berdasarkan model regresi, terdapat dua faktor yang mempengaruhi konsumsi beras di Indonesia, yaitu harga beras (<em>X</em>) dan pendapatan per kapita (<em>S</em>). Secara spesifik, hasil analisis menunjukkan bahwa pendapatan per kapita berperan secara signifikan dalam membentuk pola konsumsi beras di seluruh Indonesia. Ketika pendapatan per kapita meningkat sebesar satu satuan, konsumsi beras diperkirakan akan meningkat sebesar 0.00004983 satuan, dan hal ini terbukti signifikan pada tingkat signifikansi 0.05 (p-value: 0.00136).</p>
<p>Di sisi lain, harga beras tidak memberikan kontribusi signifikan terhadap perubahan konsumsi beras di Indonesia. Meskipun koefisien untuk harga beras (<em>X</em>) positif (0.1014), hasil uji statistik menunjukkan bahwa kenaikan harga beras tidak signifikan dalam mempengaruhi konsumsi beras, dengan nilai p-value sebesar 0.31922.</p>
<p>Dengan <em>R</em><sup>2</sup> sebesar 0.797, model ini mampu menjelaskan sekitar 79.7% variasi dalam konsumsi beras di tingkat nasional. F-statistic yang signifikan pada tingkat signifikansi 0.05 (p-value: 0.003767) menunjukkan bahwa setidaknya satu dari variabel independen (pendapatan per kapita atau harga beras) memiliki pengaruh yang signifikan terhadap konsumsi beras secara keseluruhan.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> s, <span class="at">data =</span> data_uasS)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x + s, data = data_uasS)

Residuals:
    Min      1Q  Median      3Q     Max 
-576.31  -45.98   23.73   89.11  381.73 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 2.538e+04  1.266e+03  20.048 1.92e-07 ***
x           1.014e-01  9.457e-02   1.072  0.31922    
s           4.983e-05  9.718e-06   5.128  0.00136 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 290.1 on 7 degrees of freedom
Multiple R-squared:  0.797, Adjusted R-squared:  0.739 
F-statistic: 13.74 on 2 and 7 DF,  p-value: 0.003767</code></pre>
</div>
</div>
<p>Secara keseluruhan, untuk koefisien X; dengan setiap satuan kenaikan harga beras (X), konsumsi beras (Y) diperkirakan meningkat sebesar 0.1014 satuan, walaupun tidak signifikan (p=0.31922). Disisi lain, untuk koefisien S: dengan setiap satuan kenaikan pendapatan per kapita (S), konsumsi beras (Y) diperkirakan meningkat sebesar 0.00004983 satuan, dan ini signifikan (p=0.00136).</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Setelah dilakukan penelitian melalui sistem regresi multivariat, maka dapat disimpulkan antara lain:</p>
<ul>
<li><p>Harga Beras (X): Tidak ada bukti yang cukup untuk menyimpulkan adanya hubungan signifikan antara harga beras dan konsumsi beras (Y) pada tingkat signifikansi 0.05 (p=0.31922).</p></li>
<li><p>Pendapatan Per Kapita (S): Ada bukti yang cukup untuk menyimpulkan adanya hubungan signifikan antara pendapatan per kapita dan konsumsi beras (Y) pada tingkat signifikansi 0.05 (p=0.00136).</p></li>
</ul>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Darma, D. C., Pusriadi, T., &amp; Hakim, Y. P. (2018). Dampak kenaikan harga komoditas sembako terhadap tingkat inflasi di Indonesia. Prosiding Seminar Nasional: Manajemen, Akuntansi, dan Perbankan, 1(1), 1048–1074. http://conferences.uin-malang.ac.id/index.php/semnasfe/article/view/821</p>
<p>Gunarsih, C. M., Kalangi, J. A. F., &amp; Tamengkel, L. F. (2021). Pengaruh Harga Terhadap Keputusan Pembelian Konsumen Di Toko Pelita Jaya Buyungon Amurang. Productivity, 2(1), 69–72. Retrieved from https://ejournal.unsrat.ac.id/v3/index.php/productivity/article/view/32911</p>
<p>Hanum, N. (2017). Analisis Pengaruh Pendapatan Terhadap Prilaku Konsumsi Mahasiswa Universitas Samudra di Kota Langsa. Jurnal Samudra Ekonomika, 1(2), 107-116.</p>
<p>Kiptia, A. (2018). Pengaruh pendapatan perkapita dan harga kebutuhan pokok terhadap tingkat konsumsi masyarakat di Tulungagung tahun 2014-2015 (Skripsi). Universitas Islam Negeri Sayyid Ali Rahmatullah. Tulungagung.</p>
<p>Kotler, P., &amp; Armstrong, G. (2016). Marketing: An Introduction (Edisi ke-13). Pearson Education.</p>
<p>Mahardani, I. A. S., &amp; Indrajaya, I. G. B. (2018). Pengaruh Harga dan Pendapatan Konsumen Terhadap Permintaan Janur Di Desa Ubud, Kabupaten Gianyar. E-Jurnal EP Unud, 7(5), 1084-1111. https://doi.org/10.1234/eep.12345 ISSN: 2303-0178</p>
<p>Mankiw. (2006). Teori Ekonomi Makro. Erlangga.</p>
<p>Maryadiningsih, E. (2021). Pengaruh Pendapatan Dan Gaya Hidup Terhadap Pola Konsumsi Masyarakat Muslim Di Surabaya Selama Masa Pandemi Covid-19 Ditinjau Dari Perspektif Etika Konsumsi Islam. Jurnal Ekonomi, Manajemen, Bisnis, dan Sosial (EMBISS), 1(4), 386–396.</p>
<p>Nasution, A. E., Putri, L. P., &amp; Lesmana, M. T. (2019). Analisis Pengaruh Harga, Promosi, Kepercayaan Dan Karakteristik Konsumen Terhadap Keputusan Pembelian Konsumen Pada 212 Mart Di Kota Medan. Proseding Seminar Nasional Kewirausahaan, 1(1), 194–199. http://jurnal.umsu.ac.id/index.php/snk/article/view/3594/3325</p>
<p>Yanti, Z., &amp; Murtala, M. (2019). Pengaruh pendapatan, jumlah anggota keluarga, dan tingkat pendidikan terhadap konsumsi rumah tangga di Kecamatan Muara Dua. Ekonomika Indonesia, 8(2), 72-81. https://doi.org/10.29103/ekonomika.v8i2.972</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>